---
specfile_path: fedora/rust-netlink-sys.spec
downstream_package_name: rust-netlink-sys
upstream_project_url: https://github.com/rust-netlink/netlink-sys
issue_repository: https://github.com/rust-netlink/netlink-sys

upstream_package_name: netlink-sys
upstream_tag_template: v{version}
copy_upstream_release_description: true

jobs:
  # This is triggered at upstream to create PR at src.fedoraproject.org/rpms/xxx
  # for updating SPEC file and upload source tarball
  - job: propose_downstream
    trigger: release
    dist_git_branches:
      - fedora-all

  # This is triggered at Fedora dist-git for creating koji build after
  # PR in src.fedoraproject.org been merged.
  - job: koji_build
    trigger: commit
    allowed_pr_authors: ["packit-stg", "packit"]
    dist_git_branches:
      - fedora-all

  # This is triggered at Fedora messaging bus about koji build finished.
  - job: bodhi_update
    trigger: commit
    dist_git_branches:
      - fedora-branched
